### ISSUE TITLE
Error Code format needs to be more complete

### ISSUE THREAD

**Issue by rjnienaber** [CurrencyCloud/currencycloud-js#1]
Here is an example script with an incorrect currency code:

```javascript
var currencyCloud = require('currency-cloud');

currencyCloud.authentication.login({
  environment: 'demo',
  loginId: '<login>',
  apiKey: '<password>'
})
.then(function() {
  return currencyCloud.reference.getBeneficiaryRequiredDetails({
    currency: 'EU',  // invalid currency code
    bankAccountCountry: 'DE'
  });
})
.then(console.log)
.catch(console.log);
```

The api will throw an error and we'll get a response like the following:
```json
{ [APIerror: beneficiary_required_details_failed]
  name: 'APIerror',
  message: 'beneficiary_required_details_failed',
  cause: 
   { statusCode: 400,
     error: 
      { errorCode: 'beneficiary_required_details_failed',
        errorMessages: [Object] } } }
```

There are [a few details missing](https://github.com/CurrencyCloud/currencycloud-ruby#errors) here and that would be listed in other apis. Here is some example output from the Ruby SDK:

```yaml
CurrencyCloud::BadRequestError: CurrencyCloud::BadRequestError
---
platform: ruby-2.2.0
request:
  parameters:
    currency: EU
    bank_account_country: DE
  verb: get
  url: https://devapi.thecurrencycloud.com/v2/reference/beneficiary_required_details
response:
  status_code: 400
  date: Wed, 04 Nov 2015 07:27:15 GMT
  request_id: 2911773143226628915
errors:
- field: currency
  code: currency_is_in_invalid_format
  message: currency is not a valid ISO 4217 currency code
  params:
    type: currency
```

Also note that when converting the error to string for display, it converts it to YAML. This is standardized across all other SDKs and I would expect it to be the same for this one as well.
